# this is redis config file
[list]
    [list.default]
        proxy_list = ["127.0.0.1:6379"]
        conn_timeout = 5000
        password = "qwe123"
        db = 0
        read_timeout = 1000
        write_timeout = 1000
        max_active = 200
        max_idle = 500